/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SyllabusAI API
 * AI powered learning
 * OpenAPI spec version: 1.0.0
 */
import type { ChapterContent } from './chapterContent';

export interface Chapter {
  content?: ChapterContent;
  description: string;
  id: number;
  is_read: boolean;
  title: string;
}
