/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SyllabusAI API
 * AI powered learning
 * OpenAPI spec version: 1.0.0
 */
import type { History } from './history';

export interface ChatRequest {
  history: History[];
  message: string;
}
