/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SyllabusAI API
 * AI powered learning
 * OpenAPI spec version: 1.0.0
 */

export interface GetChapterResponse {
  content: string;
  id: number;
  is_read: boolean;
  short_description: string;
  title: string;
  topic_id: number;
}
