/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SyllabusAI API
 * AI powered learning
 * OpenAPI spec version: 1.0.0
 */

export type HistoryUserType = typeof HistoryUserType[keyof typeof HistoryUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoryUserType = {
  user: 'user',
  bot: 'bot',
} as const;
