/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SyllabusAI API
 * AI powered learning
 * OpenAPI spec version: 1.0.0
 */
import type { HistoryUserType } from './historyUserType';

export interface History {
  message: string;
  user_type: HistoryUserType;
}
