/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * SyllabusAI API
 * AI powered learning
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponsePicture } from './userResponsePicture';
import type { UserResponseToken } from './userResponseToken';

export interface UserResponse {
  email: string;
  id: number;
  is_active: boolean;
  name: string;
  picture?: UserResponsePicture;
  token?: UserResponseToken;
}
