services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
      - /app/.venv
    command: poetry run fastapi dev app/main.py --host 0.0.0.0 --port 8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
