/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Chapter = {
  name: string;
  description: string;
  slug: string;
};

export type GenerateChapterRequest = {
  chapter: string;
  description: string;
};

export type GenerateChapterResponse = {
  content: string;
};

export type GenerateChaptersRequest = {
  topic: string;
};

export type GenerateChaptersResponse = {
  topic: string;
  chapters: Chapter[];
};

export type GenerateQuizRequest = {
  topic: string;
  content: string;
};

export type GenerateQuizResponse = {
  questions: Question[];
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type Question = {
  question: string;
  correctOptionIndex: number;
  options: string[];
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
